//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  artikel: Artikel;
  artikelConnection: ArtikelConnection;
  ziel: Ziel;
  zielConnection: ZielConnection;
  deal: Deal;
  dealConnection: DealConnection;
  settings: Settings;
  settingsConnection: SettingsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArtikelArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArtikelConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtikelFilter>;
};


export type QueryZielArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryZielConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ZielFilter>;
};


export type QueryDealArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDealConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DealFilter>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};

export type DocumentFilter = {
  artikel?: InputMaybe<ArtikelFilter>;
  ziel?: InputMaybe<ZielFilter>;
  deal?: InputMaybe<DealFilter>;
  settings?: InputMaybe<SettingsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Artikel | Ziel | Deal | Settings | Folder;

export type Artikel = Node & Document & {
  __typename?: 'Artikel';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  publishDate?: Maybe<Scalars['String']['output']>;
  readTime?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ArtikelFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  category?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  readTime?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ArtikelConnectionEdges = {
  __typename?: 'ArtikelConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Artikel>;
};

export type ArtikelConnection = Connection & {
  __typename?: 'ArtikelConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArtikelConnectionEdges>>>;
};

export type ZielHighlights = {
  __typename?: 'ZielHighlights';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type Ziel = Node & Document & {
  __typename?: 'Ziel';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  region?: Maybe<Scalars['String']['output']>;
  country?: Maybe<Scalars['String']['output']>;
  priceFrom?: Maybe<Scalars['String']['output']>;
  bestTime?: Maybe<Scalars['String']['output']>;
  highlights?: Maybe<Array<Maybe<ZielHighlights>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ZielHighlightsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type ZielFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  region?: InputMaybe<StringFilter>;
  country?: InputMaybe<StringFilter>;
  priceFrom?: InputMaybe<StringFilter>;
  bestTime?: InputMaybe<StringFilter>;
  highlights?: InputMaybe<ZielHighlightsFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ZielConnectionEdges = {
  __typename?: 'ZielConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Ziel>;
};

export type ZielConnection = Connection & {
  __typename?: 'ZielConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ZielConnectionEdges>>>;
};

export type Deal = Node & Document & {
  __typename?: 'Deal';
  title: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  destination?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['Float']['output']>;
  originalPrice?: Maybe<Scalars['Float']['output']>;
  discount?: Maybe<Scalars['String']['output']>;
  stars?: Maybe<Scalars['Float']['output']>;
  bookingUrl?: Maybe<Scalars['String']['output']>;
  expiresAt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type DealFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  destination?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  originalPrice?: InputMaybe<NumberFilter>;
  discount?: InputMaybe<StringFilter>;
  stars?: InputMaybe<NumberFilter>;
  bookingUrl?: InputMaybe<StringFilter>;
  expiresAt?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type DealConnectionEdges = {
  __typename?: 'DealConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Deal>;
};

export type DealConnection = Connection & {
  __typename?: 'DealConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DealConnectionEdges>>>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  logo?: Maybe<Scalars['String']['output']>;
  siteTitle?: Maybe<Scalars['String']['output']>;
  siteDescription?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SettingsFilter = {
  logo?: InputMaybe<ImageFilter>;
  siteTitle?: InputMaybe<StringFilter>;
  siteDescription?: InputMaybe<StringFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateArtikel: Artikel;
  createArtikel: Artikel;
  updateZiel: Ziel;
  createZiel: Ziel;
  updateDeal: Deal;
  createDeal: Deal;
  updateSettings: Settings;
  createSettings: Settings;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateArtikelArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtikelMutation;
};


export type MutationCreateArtikelArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtikelMutation;
};


export type MutationUpdateZielArgs = {
  relativePath: Scalars['String']['input'];
  params: ZielMutation;
};


export type MutationCreateZielArgs = {
  relativePath: Scalars['String']['input'];
  params: ZielMutation;
};


export type MutationUpdateDealArgs = {
  relativePath: Scalars['String']['input'];
  params: DealMutation;
};


export type MutationCreateDealArgs = {
  relativePath: Scalars['String']['input'];
  params: DealMutation;
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};

export type DocumentUpdateMutation = {
  artikel?: InputMaybe<ArtikelMutation>;
  ziel?: InputMaybe<ZielMutation>;
  deal?: InputMaybe<DealMutation>;
  settings?: InputMaybe<SettingsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  artikel?: InputMaybe<ArtikelMutation>;
  ziel?: InputMaybe<ZielMutation>;
  deal?: InputMaybe<DealMutation>;
  settings?: InputMaybe<SettingsMutation>;
};

export type ArtikelMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ZielHighlightsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type ZielMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  region?: InputMaybe<Scalars['String']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
  priceFrom?: InputMaybe<Scalars['String']['input']>;
  bestTime?: InputMaybe<Scalars['String']['input']>;
  highlights?: InputMaybe<Array<InputMaybe<ZielHighlightsMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type DealMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  destination?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  originalPrice?: InputMaybe<Scalars['Float']['input']>;
  discount?: InputMaybe<Scalars['String']['input']>;
  stars?: InputMaybe<Scalars['Float']['input']>;
  bookingUrl?: InputMaybe<Scalars['String']['input']>;
  expiresAt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SettingsMutation = {
  logo?: InputMaybe<Scalars['String']['input']>;
  siteTitle?: InputMaybe<Scalars['String']['input']>;
  siteDescription?: InputMaybe<Scalars['String']['input']>;
};

export type ArtikelPartsFragment = { __typename: 'Artikel', title: string, subtitle?: string | null, heroImage?: string | null, category?: string | null, author?: string | null, publishDate?: string | null, readTime?: string | null, body?: any | null };

export type ZielPartsFragment = { __typename: 'Ziel', title: string, subtitle?: string | null, heroImage?: string | null, region?: string | null, country?: string | null, priceFrom?: string | null, bestTime?: string | null, body?: any | null, highlights?: Array<{ __typename: 'ZielHighlights', title?: string | null, description?: string | null, image?: string | null } | null> | null };

export type DealPartsFragment = { __typename: 'Deal', title: string, image?: string | null, destination?: string | null, price?: number | null, originalPrice?: number | null, discount?: string | null, stars?: number | null, bookingUrl?: string | null, expiresAt?: string | null, body?: any | null };

export type SettingsPartsFragment = { __typename: 'Settings', logo?: string | null, siteTitle?: string | null, siteDescription?: string | null };

export type ArtikelQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArtikelQuery = { __typename?: 'Query', artikel: { __typename: 'Artikel', id: string, title: string, subtitle?: string | null, heroImage?: string | null, category?: string | null, author?: string | null, publishDate?: string | null, readTime?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ArtikelConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtikelFilter>;
}>;


export type ArtikelConnectionQuery = { __typename?: 'Query', artikelConnection: { __typename?: 'ArtikelConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArtikelConnectionEdges', cursor: string, node?: { __typename: 'Artikel', id: string, title: string, subtitle?: string | null, heroImage?: string | null, category?: string | null, author?: string | null, publishDate?: string | null, readTime?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ZielQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ZielQuery = { __typename?: 'Query', ziel: { __typename: 'Ziel', id: string, title: string, subtitle?: string | null, heroImage?: string | null, region?: string | null, country?: string | null, priceFrom?: string | null, bestTime?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, highlights?: Array<{ __typename: 'ZielHighlights', title?: string | null, description?: string | null, image?: string | null } | null> | null } };

export type ZielConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ZielFilter>;
}>;


export type ZielConnectionQuery = { __typename?: 'Query', zielConnection: { __typename?: 'ZielConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ZielConnectionEdges', cursor: string, node?: { __typename: 'Ziel', id: string, title: string, subtitle?: string | null, heroImage?: string | null, region?: string | null, country?: string | null, priceFrom?: string | null, bestTime?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, highlights?: Array<{ __typename: 'ZielHighlights', title?: string | null, description?: string | null, image?: string | null } | null> | null } | null } | null> | null } };

export type DealQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DealQuery = { __typename?: 'Query', deal: { __typename: 'Deal', id: string, title: string, image?: string | null, destination?: string | null, price?: number | null, originalPrice?: number | null, discount?: string | null, stars?: number | null, bookingUrl?: string | null, expiresAt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DealConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DealFilter>;
}>;


export type DealConnectionQuery = { __typename?: 'Query', dealConnection: { __typename?: 'DealConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DealConnectionEdges', cursor: string, node?: { __typename: 'Deal', id: string, title: string, image?: string | null, destination?: string | null, price?: number | null, originalPrice?: number | null, discount?: string | null, stars?: number | null, bookingUrl?: string | null, expiresAt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, logo?: string | null, siteTitle?: string | null, siteDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, logo?: string | null, siteTitle?: string | null, siteDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ArtikelPartsFragmentDoc = gql`
    fragment ArtikelParts on Artikel {
  __typename
  title
  subtitle
  heroImage
  category
  author
  publishDate
  readTime
  body
}
    `;
export const ZielPartsFragmentDoc = gql`
    fragment ZielParts on Ziel {
  __typename
  title
  subtitle
  heroImage
  region
  country
  priceFrom
  bestTime
  highlights {
    __typename
    title
    description
    image
  }
  body
}
    `;
export const DealPartsFragmentDoc = gql`
    fragment DealParts on Deal {
  __typename
  title
  image
  destination
  price
  originalPrice
  discount
  stars
  bookingUrl
  expiresAt
  body
}
    `;
export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  logo
  siteTitle
  siteDescription
}
    `;
export const ArtikelDocument = gql`
    query artikel($relativePath: String!) {
  artikel(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArtikelParts
  }
}
    ${ArtikelPartsFragmentDoc}`;
export const ArtikelConnectionDocument = gql`
    query artikelConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArtikelFilter) {
  artikelConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArtikelParts
      }
    }
  }
}
    ${ArtikelPartsFragmentDoc}`;
export const ZielDocument = gql`
    query ziel($relativePath: String!) {
  ziel(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ZielParts
  }
}
    ${ZielPartsFragmentDoc}`;
export const ZielConnectionDocument = gql`
    query zielConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ZielFilter) {
  zielConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ZielParts
      }
    }
  }
}
    ${ZielPartsFragmentDoc}`;
export const DealDocument = gql`
    query deal($relativePath: String!) {
  deal(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DealParts
  }
}
    ${DealPartsFragmentDoc}`;
export const DealConnectionDocument = gql`
    query dealConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DealFilter) {
  dealConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DealParts
      }
    }
  }
}
    ${DealPartsFragmentDoc}`;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      artikel(variables: ArtikelQueryVariables, options?: C): Promise<{data: ArtikelQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtikelQueryVariables, query: string}> {
        return requester<{data: ArtikelQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtikelQueryVariables, query: string}, ArtikelQueryVariables>(ArtikelDocument, variables, options);
      },
    artikelConnection(variables?: ArtikelConnectionQueryVariables, options?: C): Promise<{data: ArtikelConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtikelConnectionQueryVariables, query: string}> {
        return requester<{data: ArtikelConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtikelConnectionQueryVariables, query: string}, ArtikelConnectionQueryVariables>(ArtikelConnectionDocument, variables, options);
      },
    ziel(variables: ZielQueryVariables, options?: C): Promise<{data: ZielQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ZielQueryVariables, query: string}> {
        return requester<{data: ZielQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ZielQueryVariables, query: string}, ZielQueryVariables>(ZielDocument, variables, options);
      },
    zielConnection(variables?: ZielConnectionQueryVariables, options?: C): Promise<{data: ZielConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ZielConnectionQueryVariables, query: string}> {
        return requester<{data: ZielConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ZielConnectionQueryVariables, query: string}, ZielConnectionQueryVariables>(ZielConnectionDocument, variables, options);
      },
    deal(variables: DealQueryVariables, options?: C): Promise<{data: DealQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DealQueryVariables, query: string}> {
        return requester<{data: DealQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DealQueryVariables, query: string}, DealQueryVariables>(DealDocument, variables, options);
      },
    dealConnection(variables?: DealConnectionQueryVariables, options?: C): Promise<{data: DealConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DealConnectionQueryVariables, query: string}> {
        return requester<{data: DealConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DealConnectionQueryVariables, query: string}, DealConnectionQueryVariables>(DealConnectionDocument, variables, options);
      },
    settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/5e22f88d-cb0c-468c-8114-f9e0c6d081ec/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  